### ISSUE TITLE
Spawning problem!

### ISSUE THREAD

**Issue by AlexPlus117** [SnowShock35/Quadrum#1]
{
    "name": "enderman_resource",
    "default-texture": "enderman_resource",
    "material": "ground",
    "type": "block",
    "hardness": 2.5,
    "resistance": 15.0,
    "light-level": 9,
    "redstone-level": 0,
    "burn-time": 0,
    "max-stack-size": 64,
    "mining-level": 2,
    "transparent": false,
    "collision": true,
    "flammable": false,
    "soil": false,
    "requires-tool": true,
    "drops-self": false,
    "ore-dictionary": [
        "oreEndermanResource"
    ],
    "drops": [
        {"item": "minecraft:ender_pearl", "damage": 1, "amount": "0-2"},
        {"item": "EnderIO:blockEndermanSkull", "damage": 1, "amount": "0-1"}
    ]
}

**Comment by SnowShock35** [comment]
Okay, here are the list of errors...

A. Wrong repository to report bug on. You'll want to go to http://www.github.com/dmillerw/Quadrum/issues

B. Uh add some kind of explanation of what you are trying to do and whats not working. 

C. I think u might also have wrong damage values. Remember damage values/metadata starts at 0 then 1. 

Hope this helps ;)
